version: '3'
services:
  mysql:
    image: mysql:8
    container_name: capstone_timepay_backend
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timepay
